### ISSUE TITLE
Containerize and Write CWL for BCFtools

### ISSUE THREAD

**Issue by rhshah** [msk-access/cwl-commandlinetools#31]
Version: 1.6

**Comment by rhshah** [comment]
@ionox0 Probably need to know the exact command for CWL as it will be a specific bcftools command, can you please point use to that

**Comment by ionox0** [comment]
@rhshah https://github.com/mskcc/ACCESS-Pipeline/wiki/SNV-pipeline-commands#bcftools-concat
