### ISSUE TITLE
Add REGEX Param on Picard MarkDuplicate to run it correctly so it generates proper Optical Duplicate Stats.

### ISSUE THREAD

**Issue by rhshah** [msk-access/cwl-commandlinetools#34]
Regex for EstimateLibrarySize

(?:.*):(?:\d+):(?:\w+):(?:\d+):(\d+):(\d+):(\d+):(?:\w{3}\+\w{3}).*$

https://rubular.com/r/CGrnn5WWtrh7rL

**Comment by ionox0** [comment]
I will expose the `--read_name_regex` param from MD 2.8.1, and set this as the default
