### ISSUE TITLE
Any specific reason "sample_id" is required?

### ISSUE THREAD

**Issue by rhshah** [msk-access/cwl-commandlinetools#82]
@ionox0 

https://github.com/msk-access/cwl-commandlinetools/blob/5ae32281e31fb07cd4a342dfde426ed84718607f/bwa_mem_0.7.17/bwa_mem_0.7.17.cwl#L24

**Comment by ionox0** [comment]
Some tools will pull the sample ID from the bam header (such as Manta) so I feel this should be required

**Comment by rhshah** [comment]
ok, I might be missing something here but where exactly is this unbound parameter being used? How does it become part of the bam header?

**Comment by rhshah** [comment]
#83
